baseURL = "http://blog.shaobo.fun/"
languageCode = "en-us"
title = "庄周梦蝶"
theme = "maupassant"

preserveTaxonomyNames = true
disablePathToLower = true

[author]
    name = "Hasan"

[params]
    author = "庄周梦蝶"
    subtitle = "我欲乘风破浪，又恐黄沙海洋"
    busuanzi = true

[params.utteranc]
    enable = true
    repo = "csbbo/hasan"
    issueTerm = "pathname"
    theme = "github-light"

[menu]
    [[menu.main]]
        identifier = "archives"
        name = "归档"
        url = "/archives/"
        weight = 1
    [[menu.main]]
        identifier = "friend"
        name = "友链"
        url = "/friend/"
        weight = 2
    [[menu.main]]
        identifier = "tool"
        name = "其他"
        url = "/other/"
        weight = 3
    [[menu.main]]
        identifier = "about"
        name = "关于"
        url = "/about/"
        weight = 4