baseURL = "http://blog.shaobo.fun/"
languageCode = "en-us"
title = "庄周梦蝶"
theme = "maupassant"

preserveTaxonomyNames = true
disablePathToLower = true

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[author]
    name = "Hasan"

[params]
    author = "庄周梦蝶"
    subtitle = "庄生晓梦迷蝴蝶,望帝春心托杜鹃."
    busuanzi = true

[params.utteranc]
    enable = true
    repo = "csbbo/hasan"
    issueTerm = "pathname"
    theme = "github-light"

[menu]
    [[menu.main]]
        identifier = "archives"
        name = "归档"
        url = "/tab/archives/"
        weight = 1
    [[menu.main]]
        identifier = "friend"
        name = "友链"
        url = "/tab/friend/"
        weight = 2
    [[menu.main]]
        identifier = "tool"
        name = "其他"
        url = "/tab/other/"
        weight = 3
    [[menu.main]]
        identifier = "about"
        name = "关于"
        url = "/tab/about/"
        weight = 4